### ISSUE TITLE
After "cmake .." and "make" operations in ubuntu 16.04,  I run the command "./yangtze"  but the program fails. How can I solve this problem?Thanks!

### ISSUE THREAD

**Issue by zengletian1491** [joyDeng/Yangtze_AutoImageStitch#1]
After "cmake .." and "make" operations in ubuntu 16.04,  I run the command "./yangtze" and the report presents as follows:
Number of pairs in RANSAC: 155
Best Match: (480, 357) to (83, 383)
Best Match: (455, 239) to (60, 264)
Best Match: (614, 159) to (220, 188)
Best Match: (632, 390) to (233, 416)
Number of pairs in RANSAC: 222
Best Match: (279, 221) to (611, 208)
Best Match: (12, 138) to (342, 135)
Best Match: (190, 241) to (521, 231)
Best Match: (167, 425) to (503, 416)
Number of pairs in RANSAC: 326
Best Match: (290, 276) to (569, 275)
Best Match: (84, 274) to (363, 273)
Best Match: (113, 443) to (392, 441)
Best Match: (284, 368) to (563, 368)
Image bound is: 1785, 552
Reference image done
Image 1 done
Image 2 done
Image 3 done
Output done
Number of pairs in RANSAC: 155
Best Match: (480, 357) to (83, 383)
Best Match: (455, 239) to (60, 264)
Best Match: (614, 159) to (220, 188)
Best Match: (632, 390) to (233, 416)
Number of pairs in RANSAC: 222
Best Match: (279, 221) to (611, 208)
Best Match: (12, 138) to (342, 135)
Best Match: (190, 241) to (521, 231)
Best Match: (167, 425) to (503, 416)
Number of pairs in RANSAC: 326
Best Match: (290, 276) to (569, 275)
Best Match: (84, 274) to (363, 273)
Best Match: (113, 443) to (392, 441)
Best Match: (284, 368) to (563, 368)
Image bound is: 1785, 552
Reference image done
Image 1 done
Image 2 done
Image 3 done
Output done
Number of pairs in RANSAC: 155
Best Match: (480, 357) to (83, 383)
Best Match: (455, 239) to (60, 264)
Best Match: (614, 159) to (220, 188)
Best Match: (632, 390) to (233, 416)
Number of pairs in RANSAC: 222
Best Match: (279, 221) to (611, 208)
Best Match: (12, 138) to (342, 135)
Best Match: (190, 241) to (521, 231)
Best Match: (167, 425) to (503, 416)
Number of pairs in RANSAC: 326
Best Match: (290, 276) to (569, 275)
Best Match: (84, 274) to (363, 273)
Best Match: (113, 443) to (392, 441)
Best Match: (284, 368) to (563, 368)
Image bound is: 1785, 552
Reference image done
Image 1 done
Image 2 done
Image 3 done
Output done
Image decoder error in FloatImage::read(...) for file: "/home/zeng/Work/Image_Stitching/Yangtze_AutoImageStitch/Yangtze_AutoImageStitch-master/data/input/snow/IMG_5180.jpg":
	can't fopen
terminate called after throwing an instance of 'MismatchedDimensionsException'
  what():  Image dimensions are not the same.
work.sh: line 1: 20003 Aborted                 (core dumped) ../build/yangtze

**Comment by joyDeng** [comment]
I think you need to change all the input image file name to .jpg instead of .JPG under ubuntu system.  Anyway, I fixed this, hope it's not too late.
